name: Example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Renovate example
        uses: ./
        with:
          configurationFile: example/config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
